apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sjm-tastpa-5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sjm-tastpa-5 
  name: sjm-tastpa-5
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sjm-tastpa-5 
